name: CI Pipeline
on:
push:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest
steps:
name: Checkout code
uses: actions/checkout@v2
name: Test
run: echo "Automation works!"
name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Automation Message
        run: echo "Automation works successfully!"
